### ISSUE TITLE
Support chai 4.0

### ISSUE THREAD

**Issue by jscharett** [princed/karma-chai-plugins#127]
Looks like Chai has released a new 4.0 version.  Any plans to update dependency to 4.x?

**Comment by princed** [comment]
There is such a plan, but I'm afraid we have to wait till all the plugins support it: 

- [x] domenic/sinon-chai#97
- [x] domenic/chai-as-promised#198
- [x] chaijs/chai-jquery#105
- [ ] chaijs/chai-things#58
- [x] nathanboktae/chai-dom#24

**Comment by jscharett** [comment]
https://github.com/nathanboktae/chai-dom/issues/24

**Comment by gesellix** [comment]
From https://github.com/chaijs/chai-things/issues/58#issuecomment-316061382:

> This project is currently on pause while the chai team update other chai parts. We hope to bring this plugin back up to speed around chai v5. It is dependant on chaijs/chai#585

Is there some middle ground to make this project a bit more decoupled from such impediments?

**Comment by princed** [comment]
@gesellix I don't think so. Actually updating chai-as-promised and sinon-chai would involve some build process when this plugin is getting run. So it looks like there's not such so much sense in maintaining it anymore.

In our project we just imported sinon, chai and all the required plugins directly into a test entry point, because you can't avoid having an entry point even for tests these days anyway.
